version: '3.7'
services:
  mysql:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db/:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: audio
      MYSQL_USER: audiouser
      MYSQL_PASSWORD: audiopass
  predict:
    image: audio:latest
    ports:
      - 5000:5000
    links:
      - "mysql"
    depends_on:
      - "mysql"
    restart: on-failure:10
volumes:
    db_data:
